import 'jquery';
import 'selectize';
import './style';
import './js/scriptLoader';
import './js/breakpoints';
import './js/init';
import './js/initGallery';
import './sprites';

import './modules/popup/popup.js';

import './modules/header/header.js';
import './modules/menu/menu.js';
import './modules/search/search.js';
import './modules/footer/footer.js';
import './modules/frontSlider/frontSlider.js';
// import './modules/hints/hints.js';
import './modules/bests/bests.js';
// import './modules/about/about.js';
import './modules/dealer/dealer.js';
import './modules/services/services.js';
import './modules/calculator/calculator.js';
import './modules/history/history.js';
import './modules/testimonials/testimonials.js';
import './modules/banners/banners.js';
import './modules/breadcrumbs/breadcrumbs.js';
import './modules/dealers/dealers.js';
import './modules/partners/partners.js';
import './modules/categories/categories.js';
import './modules/catalog/catalog.js';
import './modules/filter/filter.js';
import './modules/pagination/pagination.js';
import './modules/manufacture/manufacture.js';
import './modules/service/service.js';
import './modules/serviceHead/serviceHead.js';
import './modules/deliveryBullets/deliveryBullets.js';
import './modules/deliveryCalculator/deliveryCalculator.js';
import './modules/frontCalculator/frontCalculator.js';
import './modules/paymentTypes/paymentTypes.js';
import './modules/paymentCalculator/paymentCalculator.js';
import './modules/individual/individual.js';
import './modules/paymentForm/paymentForm.js';
import './modules/paymentInfo/paymentInfo.js';
import './modules/product/product.js';
import './modules/productDescription/productDescription.js';
import './modules/productBuy/productBuy.js';
import './modules/vip/vip.js';
import './modules/timeSave/timeSave.js';
import './modules/brands/brands.js';
import './modules/infoPage/infoPage.js';
import './modules/related/related.js';
import './modules/notFound/notFound.js';
import './modules/cart/cart.js';
import './modules/checkout/checkout.js';
import './modules/checkoutStep/checkoutStep.js';
import './modules/cartPopup/cartPopup.js';

import './modules/frontCategories/frontCategories.js';
