import "./style/banner.scss";
import "destyle.css/destyle.css";
// import 'selectize/dist/css/selectize.css';
import 'nouislider/dist/nouislider.css';
// import 'swiper/swiper-bundle.css';

import "./style/blocks/wpcf7.scss";
import "./style/blocks/btn.scss";
import "./style/blocks/flatBtn.scss";
import "./style/blocks/checkbox.scss";
import "./style/blocks/input.scss";
import "./style/blocks/select.scss";
import "./style/blocks/slider.scss";
import "./style/blocks/card.scss";
import "./style/fonts.scss";
import "./style/common.scss";
import "./style/typography.scss";

// import './modules/photoswipe/photoswipe.scss';
// import './modules/photoswipe/default-skin.scss';

import './modules/popup/popup.scss';
import './modules/header/header.scss';
import './modules/menu/menu.scss';
import './modules/search/search.scss';
import './modules/footer/footer.scss';
import './modules/frontSlider/frontSlider.scss';
import './modules/hints/hints.scss';
import './modules/bests/bests.scss';
import './modules/about/about.scss';
import './modules/dealer/dealer.scss';
import './modules/services/services.scss';
import './modules/calculator/calculator.scss';
import './modules/history/history.scss';
import './modules/testimonials/testimonials.scss';
import './modules/banners/banners.scss';
import './modules/breadcrumbs/breadcrumbs.scss';
import './modules/dealers/dealers.scss';
import './modules/partners/partners.scss';
import './modules/categories/categories.scss';
import './modules/catalog/catalog.scss';
import './modules/filter/filter.scss';
import './modules/pagination/pagination.scss';
